# Default values for gitbucket.

image:
  repository: dmartinlozano/gitbucket
  tag: "latest"
  # pullPolicy: IfNotPresent

gitbucket:
  # GitBucket command line options.
  options:

javavm:
  # JVM options.
  options:

# An external database is strongly recommended.
# Default to H2.
# https://github.com/gitbucket/gitbucket/wiki/External-database-configuration
externalDatabase:
  url:
  user:
  password:

configFromMap:
  enabled: false
  name:


# GitBucket requires a Persisvent Volume to store data.
persistentVolume:
  # Name of the Existing Persistent Volume Claim.
  # If defined, PVC must be created manually before volume will be bound.
  existingClaim:

  # Persistent volume size.
  # This must be set for dynamic provisioning.
  size: 10Gi

  #storageClass:
  #annotations: {}
  accessModes:
    - ReadWriteOnce

# Set memory limit to prevent JVM eating whole host memory.
resources:
  limits:
    memory: 1Gi
  requests:
    memory: 1Gi

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - gitbucket.example.com
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

service:
  type: ClusterIP

# GitBucket may not work with shared volumes.
replicaCount: 1

nodeSelector: {}

tolerations: []

affinity: {}
