version: '2'

services:

  db:
    image: postgres:9-alpine
    environment:
      POSTGRES_DB: testlinkdb
      POSTGRES_USER: testlink
      POSTGRES_PASSWORD: testlinkrocks
    ports:
      - 5432
    volumes:
      - db-data:/var/lib/postgresql/data


  testlink:
    build: .
    environment:
      BASE_PATH: /testlink
      DATABASE_TYPE: postgres
      DATABASE_HOST: "db:5432"
      DATABASE_NAME: testlinkdb
      DATABASE_USER: testlink
      DATABASE_PASS: testlinkrocks
    ports:
      - 8080:80
    links:
      - db
    depends_on:
      - db

volumes:
  db-data:
    driver: local
  testlink_data:
    driver: local
