apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gitbucket.fullname" . }}
  labels:
    app: {{ template "gitbucket.name" . }}
    chart: {{ template "gitbucket.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- if .Values.externalDatabase.password }}
  externalDatabasePassword: {{ .Values.externalDatabase.password | b64enc | quote }}
{{- end }}